# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_user_field_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_lesson_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
